### PR TITLE
change the endpoint route to accomodate with the naming scheme

### PR DESCRIPTION
**Pull request by c-castillo**

### CODE REVIEW

**Review by zachferland — APPROVED** [review]

**Comment by oed** [comment]
@c-castillo is this deployed? It seems like it would break the current library. we need the endpoint to be availible at `'https://aic67onptg.execute-api.us-west-2.amazonaws.com/develop/graphql'` as well going forward not to break past libraries!

**Comment by c-castillo** [comment]
@oed The endpoint is automatically generated by aws. The new name is just a shortcut to that endpoint so we are good.

**Comment by oed** [comment]
@c-castillo with this update though the url would become `'https://aic67onptg.execute-api.us-west-2.amazonaws.com/develop/'` right though since we removed the `/graphql`?

**Comment by c-castillo** [comment]
@oed yes, that's the only part that changes.

**Comment by c-castillo** [comment]
@oed Since it's not deployed yet, there's still time to update the lib without any breaking changes.

**Comment by oed** [comment]
@c-castillo if it changes it will break the already released library. We need to make it available on both with and without `/graphql`

**Comment by oed** [comment]
Fixed by #15

**Pull request merged**
